# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aris/Desktop/Geant4/geant4-install/LiDiffusion-v2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aris/Desktop/Geant4/geant4-install/LiDiffusion-v2-build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aris/Desktop/Geant4/geant4-install/LiDiffusion-v2-build/CMakeFiles /home/aris/Desktop/Geant4/geant4-install/LiDiffusion-v2-build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aris/Desktop/Geant4/geant4-install/LiDiffusion-v2-build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LiDiffusion

# Build rule for target.
LiDiffusion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LiDiffusion
.PHONY : LiDiffusion

# fast build rule for target.
LiDiffusion/fast:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/build
.PHONY : LiDiffusion/fast

#=============================================================================
# Target rules for targets named LiDiffusionCode

# Build rule for target.
LiDiffusionCode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LiDiffusionCode
.PHONY : LiDiffusionCode

# fast build rule for target.
LiDiffusionCode/fast:
	$(MAKE) -f CMakeFiles/LiDiffusionCode.dir/build.make CMakeFiles/LiDiffusionCode.dir/build
.PHONY : LiDiffusionCode/fast

LiDiffusion.o: LiDiffusion.cc.o

.PHONY : LiDiffusion.o

# target to build an object file
LiDiffusion.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/LiDiffusion.cc.o
.PHONY : LiDiffusion.cc.o

LiDiffusion.i: LiDiffusion.cc.i

.PHONY : LiDiffusion.i

# target to preprocess a source file
LiDiffusion.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/LiDiffusion.cc.i
.PHONY : LiDiffusion.cc.i

LiDiffusion.s: LiDiffusion.cc.s

.PHONY : LiDiffusion.s

# target to generate assembly for a file
LiDiffusion.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/LiDiffusion.cc.s
.PHONY : LiDiffusion.cc.s

src/LiActionInitialization.o: src/LiActionInitialization.cc.o

.PHONY : src/LiActionInitialization.o

# target to build an object file
src/LiActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiActionInitialization.cc.o
.PHONY : src/LiActionInitialization.cc.o

src/LiActionInitialization.i: src/LiActionInitialization.cc.i

.PHONY : src/LiActionInitialization.i

# target to preprocess a source file
src/LiActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiActionInitialization.cc.i
.PHONY : src/LiActionInitialization.cc.i

src/LiActionInitialization.s: src/LiActionInitialization.cc.s

.PHONY : src/LiActionInitialization.s

# target to generate assembly for a file
src/LiActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiActionInitialization.cc.s
.PHONY : src/LiActionInitialization.cc.s

src/LiDetectorConstruction.o: src/LiDetectorConstruction.cc.o

.PHONY : src/LiDetectorConstruction.o

# target to build an object file
src/LiDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiDetectorConstruction.cc.o
.PHONY : src/LiDetectorConstruction.cc.o

src/LiDetectorConstruction.i: src/LiDetectorConstruction.cc.i

.PHONY : src/LiDetectorConstruction.i

# target to preprocess a source file
src/LiDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiDetectorConstruction.cc.i
.PHONY : src/LiDetectorConstruction.cc.i

src/LiDetectorConstruction.s: src/LiDetectorConstruction.cc.s

.PHONY : src/LiDetectorConstruction.s

# target to generate assembly for a file
src/LiDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiDetectorConstruction.cc.s
.PHONY : src/LiDetectorConstruction.cc.s

src/LiDetectorMessenger.o: src/LiDetectorMessenger.cc.o

.PHONY : src/LiDetectorMessenger.o

# target to build an object file
src/LiDetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiDetectorMessenger.cc.o
.PHONY : src/LiDetectorMessenger.cc.o

src/LiDetectorMessenger.i: src/LiDetectorMessenger.cc.i

.PHONY : src/LiDetectorMessenger.i

# target to preprocess a source file
src/LiDetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiDetectorMessenger.cc.i
.PHONY : src/LiDetectorMessenger.cc.i

src/LiDetectorMessenger.s: src/LiDetectorMessenger.cc.s

.PHONY : src/LiDetectorMessenger.s

# target to generate assembly for a file
src/LiDetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiDetectorMessenger.cc.s
.PHONY : src/LiDetectorMessenger.cc.s

src/LiEventAction.o: src/LiEventAction.cc.o

.PHONY : src/LiEventAction.o

# target to build an object file
src/LiEventAction.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiEventAction.cc.o
.PHONY : src/LiEventAction.cc.o

src/LiEventAction.i: src/LiEventAction.cc.i

.PHONY : src/LiEventAction.i

# target to preprocess a source file
src/LiEventAction.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiEventAction.cc.i
.PHONY : src/LiEventAction.cc.i

src/LiEventAction.s: src/LiEventAction.cc.s

.PHONY : src/LiEventAction.s

# target to generate assembly for a file
src/LiEventAction.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiEventAction.cc.s
.PHONY : src/LiEventAction.cc.s

src/LiPrimaryGeneratorAction.o: src/LiPrimaryGeneratorAction.cc.o

.PHONY : src/LiPrimaryGeneratorAction.o

# target to build an object file
src/LiPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiPrimaryGeneratorAction.cc.o
.PHONY : src/LiPrimaryGeneratorAction.cc.o

src/LiPrimaryGeneratorAction.i: src/LiPrimaryGeneratorAction.cc.i

.PHONY : src/LiPrimaryGeneratorAction.i

# target to preprocess a source file
src/LiPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiPrimaryGeneratorAction.cc.i
.PHONY : src/LiPrimaryGeneratorAction.cc.i

src/LiPrimaryGeneratorAction.s: src/LiPrimaryGeneratorAction.cc.s

.PHONY : src/LiPrimaryGeneratorAction.s

# target to generate assembly for a file
src/LiPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiPrimaryGeneratorAction.cc.s
.PHONY : src/LiPrimaryGeneratorAction.cc.s

src/LiPrimaryGeneratorMessenger.o: src/LiPrimaryGeneratorMessenger.cc.o

.PHONY : src/LiPrimaryGeneratorMessenger.o

# target to build an object file
src/LiPrimaryGeneratorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiPrimaryGeneratorMessenger.cc.o
.PHONY : src/LiPrimaryGeneratorMessenger.cc.o

src/LiPrimaryGeneratorMessenger.i: src/LiPrimaryGeneratorMessenger.cc.i

.PHONY : src/LiPrimaryGeneratorMessenger.i

# target to preprocess a source file
src/LiPrimaryGeneratorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiPrimaryGeneratorMessenger.cc.i
.PHONY : src/LiPrimaryGeneratorMessenger.cc.i

src/LiPrimaryGeneratorMessenger.s: src/LiPrimaryGeneratorMessenger.cc.s

.PHONY : src/LiPrimaryGeneratorMessenger.s

# target to generate assembly for a file
src/LiPrimaryGeneratorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiPrimaryGeneratorMessenger.cc.s
.PHONY : src/LiPrimaryGeneratorMessenger.cc.s

src/LiRun.o: src/LiRun.cc.o

.PHONY : src/LiRun.o

# target to build an object file
src/LiRun.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiRun.cc.o
.PHONY : src/LiRun.cc.o

src/LiRun.i: src/LiRun.cc.i

.PHONY : src/LiRun.i

# target to preprocess a source file
src/LiRun.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiRun.cc.i
.PHONY : src/LiRun.cc.i

src/LiRun.s: src/LiRun.cc.s

.PHONY : src/LiRun.s

# target to generate assembly for a file
src/LiRun.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiRun.cc.s
.PHONY : src/LiRun.cc.s

src/LiRunAction.o: src/LiRunAction.cc.o

.PHONY : src/LiRunAction.o

# target to build an object file
src/LiRunAction.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiRunAction.cc.o
.PHONY : src/LiRunAction.cc.o

src/LiRunAction.i: src/LiRunAction.cc.i

.PHONY : src/LiRunAction.i

# target to preprocess a source file
src/LiRunAction.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiRunAction.cc.i
.PHONY : src/LiRunAction.cc.i

src/LiRunAction.s: src/LiRunAction.cc.s

.PHONY : src/LiRunAction.s

# target to generate assembly for a file
src/LiRunAction.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiRunAction.cc.s
.PHONY : src/LiRunAction.cc.s

src/LiSteppingAction.o: src/LiSteppingAction.cc.o

.PHONY : src/LiSteppingAction.o

# target to build an object file
src/LiSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiSteppingAction.cc.o
.PHONY : src/LiSteppingAction.cc.o

src/LiSteppingAction.i: src/LiSteppingAction.cc.i

.PHONY : src/LiSteppingAction.i

# target to preprocess a source file
src/LiSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiSteppingAction.cc.i
.PHONY : src/LiSteppingAction.cc.i

src/LiSteppingAction.s: src/LiSteppingAction.cc.s

.PHONY : src/LiSteppingAction.s

# target to generate assembly for a file
src/LiSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/LiSteppingAction.cc.s
.PHONY : src/LiSteppingAction.cc.s

src/PhysicsList.o: src/PhysicsList.cc.o

.PHONY : src/PhysicsList.o

# target to build an object file
src/PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/PhysicsList.cc.o
.PHONY : src/PhysicsList.cc.o

src/PhysicsList.i: src/PhysicsList.cc.i

.PHONY : src/PhysicsList.i

# target to preprocess a source file
src/PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/PhysicsList.cc.i
.PHONY : src/PhysicsList.cc.i

src/PhysicsList.s: src/PhysicsList.cc.s

.PHONY : src/PhysicsList.s

# target to generate assembly for a file
src/PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/LiDiffusion.dir/build.make CMakeFiles/LiDiffusion.dir/src/PhysicsList.cc.s
.PHONY : src/PhysicsList.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... LiDiffusion"
	@echo "... LiDiffusionCode"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... LiDiffusion.o"
	@echo "... LiDiffusion.i"
	@echo "... LiDiffusion.s"
	@echo "... src/LiActionInitialization.o"
	@echo "... src/LiActionInitialization.i"
	@echo "... src/LiActionInitialization.s"
	@echo "... src/LiDetectorConstruction.o"
	@echo "... src/LiDetectorConstruction.i"
	@echo "... src/LiDetectorConstruction.s"
	@echo "... src/LiDetectorMessenger.o"
	@echo "... src/LiDetectorMessenger.i"
	@echo "... src/LiDetectorMessenger.s"
	@echo "... src/LiEventAction.o"
	@echo "... src/LiEventAction.i"
	@echo "... src/LiEventAction.s"
	@echo "... src/LiPrimaryGeneratorAction.o"
	@echo "... src/LiPrimaryGeneratorAction.i"
	@echo "... src/LiPrimaryGeneratorAction.s"
	@echo "... src/LiPrimaryGeneratorMessenger.o"
	@echo "... src/LiPrimaryGeneratorMessenger.i"
	@echo "... src/LiPrimaryGeneratorMessenger.s"
	@echo "... src/LiRun.o"
	@echo "... src/LiRun.i"
	@echo "... src/LiRun.s"
	@echo "... src/LiRunAction.o"
	@echo "... src/LiRunAction.i"
	@echo "... src/LiRunAction.s"
	@echo "... src/LiSteppingAction.o"
	@echo "... src/LiSteppingAction.i"
	@echo "... src/LiSteppingAction.s"
	@echo "... src/PhysicsList.o"
	@echo "... src/PhysicsList.i"
	@echo "... src/PhysicsList.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

