/control/verbose 0
/control/saveHistory
/run/verbose 0
/control/cout/ignoreThreadsExcept 0
/event/verbose 0
/tracking/verbose 0


/LiDiffusionCode/geometry/createSampleMaterial 3.15 Mg 1 F 2
/LiDiffusionCode/geometry/setSampleWidth     7 mm
/LiDiffusionCode/geometry/setSampleDepth     500 um
/LiDiffusionCode/geometry/setSubstrateWidth  7 mm
/LiDiffusionCode/geometry/setSubstrateDepth  500 um
/LiDiffusionCode/geometry/setDetectorWidth   0.4 mm
/LiDiffusionCode/geometry/setDetectorDepth   0.1 mm
/LiDiffusionCode/geometry/setDetectorRadious 5.72 mm   #5.2x1.1

/LiDiffusionCode/geometry/setTime 0 s
/LiDiffusionCode/geometry/LiIonsPerPulse 1000000
/LiDiffusionCode/geometry/setBeamOnTime 1 s
/LiDiffusionCode/geometry/diagnostics 1
/LiDiffusionCode/geometry/setFilename TiO2
/LiDiffusionCode/geometry/setSRIMfilename TiO2_25keV
/LiDiffusionCode/geometry/setDiffusionRate 3e-9
/LiDiffusionCode/geometry/setBoundaryCondition accumulative



/LiDiffusionCode/geometry/update

/run/beamOn 100000000
